import React from "react";
import FooterLayout from "../components/FooterLayout";
import MainLayout from "../components/MainLayout";


function policy() {
  return (
    <>
      <MainLayout title={"Privacy Policy"}>
        <div className="page-header mt-6">
          <h3 className="page-title ">Privacy Policy</h3>
        </div>

        <div className="card p-6">
          <p>
            ghmade (“we,” “our,” or “us”) is committed to protecting
            your privacy. This Privacy Policy explains how your personal
            information is collected, used, and disclosed by ghmade.
          </p>
          <p>
            {" "}
            This Privacy Policy applies to our web and mobile application,
            ghmade, and its associated subdomains (collectively, our
            “Service”) alongside our application, ghmade. By
            accessing or using our Service, you signify that you have read,
            understood, and agree to our collection, storage, use, and
            disclosure of your personal information as described in this Privacy
            Policy and our Terms of Service.
          </p>
          <h3>
            <strong>Meanings</strong>
          </h3>
          <p>For this Privacy Policy:</p>
          <p className="ml-4">
            <li>
              {" "}
              You is referred to the person who accessed the Service, or the
              company, or other legal entity on behalf of which such individual
              is accessing or using the Service, as applicable.
            </li>
            <li>
              Company (referred to as either "the Company", "We", "Us" or "Our"
              in this Agreement) refers to AMALITECH,
            </li>
            <li>AMALITECH</li>
            <li>
              Web or mobile application is referred to ghmade,
              accessible from www.communityplatform.com, Google Playstore or App
              Store. Service is referred to the ghmade.
            </li>
            <li>
              Service Provider means any natural or legal person who processes
              the data on behalf of the Company. It refers to third party
              companies or individuals employed by the Company to facilitate the
              Service, to provide the Service on behalf of the Company, to
              perform services related to the Service or to assist the Company
              in analyzing how the Service is used.
            </li>
            <li>
              Personal Data is any information that relates to an identified or
              identifiable individual.
            </li>
            <li>
              Cookies are a small amount of data generated by a website and
              saved by your web browser. Its purpose is to remember information
              about you, similar to a preference file created by a software
              application.
            </li>
            <li>
              Device could be any device with internet and can access the
              service, such as a mobile phone, a computer, or a digital tablet.
            </li>
            <li>
              Usage Data is referred to the data that’s been collected
              automatically, either generated by the use of the Service or from
              the Service infrastructure itself. For example, how many times the
              user accessed the platform.
            </li>
          </p>

          <p>
            <h3>
              <strong>What Information Do We Collect?</strong>
            </h3>
            <p>
              {" "}
              We collect information from you when you use our web or mobile
              application, register on our platform, place an order, or fill out
              a form.
            </p>
            <p className="ml-4">
              <li>Name / username</li>
              <li>E-mail address</li>
              <li>Physical address</li>
              <li>Phone number</li>
            </p>
          </p>

          <p>
            We also collect information from mobile devices for a better user
            experience, although these features are completely optional:
          </p>
          <p className="ml-4">
            <li>
              {" "}
              Location (GPS): Location data helps to create an accurate
              representation of your interests, and this can be used to bring
              more targeted and relevant ads to potential customers.
            </li>
            <li>
              Camera (Pictures): Granting camera permission allows the user to
              upload images straight from their devices. You can safely deny
              camera permissions for this.
            </li>
          </p>

          <h3>
            <strong>How Do We Use the Information We Collect? </strong>
          </h3>
          <p>
            Any of the information we collect from you may be used in one of the
            following ways:
          </p>
          <p className="ml-4">
            <li>
              To personalize your experience (your information helps us to
              better respond to your individual needs)
            </li>
            <li>
              To improve our web or mobile application (we continually strive to
              improve our platform offerings based on the information and
              feedback we receive from you)
            </li>
            <li>
              To improve customer service (your information helps us to more
              effectively respond to your customer service requests and support
              needs) To process transactions
            </li>
            <li>To send periodic emails</li>
          </p>

          <h3>
            <strong>How Long Do We Keep Your Information?</strong>
          </h3>
          <p>
            We keep your information only so long as we need it to provide
            ghmade to you and fulfill the purposes described in this
            policy. This is also the case for anyone that we share your
            information with and who carries out services on our behalf. When we
            no longer need to use your information and there is no need for us
            to keep it to comply with our legal or regulatory obligations, we’ll
            either remove it from our systems or depersonalize it so that we
            can't identify you.
          </p>

          <h3>
            <strong>How Do We Protect Your Information?</strong>
          </h3>
          <p>
            {" "}
            We implement a variety of security measures to maintain the safety
            of your personal information when you place an order or enter,
            submit, or access your personal information. We offer the use of a
            secure server.{" "}
          </p>
          <p>
            The security of your personal information is central to community
            platform. We follow global industry standards to protect the
            personal information submitted to us in any transaction on the
            platform. No method of transaction over the Internet, or method of
            electronic storage, is 100% secure, however. Therefore, while we
            strive to use commercially acceptable means to protect your personal
            information, we cannot guarantee its absolute security.
          </p>
          <p>
            If you have any questions about security on our Web site, you can
            email us at info@communitypatform.com
          </p>

          <h3>
            <strong>Governing Law</strong>
          </h3>
          <p>
            {" "}
            The laws of Ghana, excluding its conflicts of law rules, shall
            govern this Agreement and your use of the web or mobile platform.
            Your use of the platform may also be subject to other local, state,
            national, or international laws.
          </p>

          <h3>
            <strong>Your Consent </strong>
          </h3>
          <p>
            {" "}
            By using our platform, registering an account, or making an order,
            you consent to this Privacy Policy.
          </p>

          <h3>
            <strong>Cookies </strong>
          </h3>
          <p>
            {" "}
            ghmade uses "Cookies" to identify the areas of our
            platform that you have visited. A Cookie is a small piece of data
            stored on your computer or mobile device by your web browser. We use
            Cookies to personalize the Content that you see on our platform.
            Most web browsers can be set to disable the use of Cookies. However,
            if you disable Cookies, you may not be able to access functionality
            on our platform correctly or at all. We never place Personally
            Identifiable Information in Cookies.
          </p>

          <h3>
            <strong>Changes to Our Privacy Policy</strong>
          </h3>
          <p>
            {" "}
            If we decide to change our privacy policy, we will post those
            changes on this page, and/or update the Privacy Policy modification
            date below.
          </p>

          <h3>
            <strong>Legal Right</strong>
          </h3>
          <p>
            It is important that the personal data we hold about you is accurate
            and current. Please keep us informed if your personal data changes
            during your relationship with us.
          </p>
          <p>
            {" "}
            Under certain circumstances, you have rights under data protection
            laws in relation to your personal data, including the right to
            access, correct or erase your personal data and restrict processing
            of your personal data.
          </p>

          <h3>
            <strong>Contact Us</strong>
          </h3>
          <p>Don't hesitate to contact us if you have any questions.</p>

          <p className="ml-4">
            <li>Via Phone Number: +233 123 456 789</li>
            <li>Via this Link: <a href="http://www.ghmade.com" target="_blank" rel="noopener noreferrer">http://www.ghmade.com</a></li>
          </p>

          <h6 className="mt-4 pb-4 d-flex justify-content-center">
            <strong> Last updated: 11/02/2020</strong>
          </h6>
        </div>
      </MainLayout>

      <FooterLayout/>
    </>
  );
}

export default policy;
