import React from 'react'
import FooterLayout from '../components/FooterLayout'
import MainLayout from '../components/MainLayout'

function termsandconditions() {
    return (
        <>
          <MainLayout title={"Terms & Conditions"}>

          <div className="page-header mt-6">
            <h3 className="page-title ">Terms & Conditions</h3>
          </div>

                <div className="card p-6">
                     <p>
                     Please read this agreement carefully before accessing or using the information and services available through the ghmade application. By accessing or using the Site, you agree to be bound by the terms and conditions below. ghmade may modify this agreement at any time, and such modifications shall be effective immediately upon posting the modified agreement on the Site. 
                     </p>
                      <p>
                      ghmade reserves the right to update these terms and conditions with/without prior notice.
                      </p> 
                      <h3><strong>Copyright and Trademark</strong></h3>
                        <p>
                        Users grant ghmade a perpetual, royalty-free, irrevocable, non-exclusive right and license to use, reproduce, modify, adapt, publish, translate, create derivative works from and distribute such Content or incorporate such Content into any form, medium, or technology now known or later developed.
                        </p>
                        <p>
                        Copyright in the material and trademarks on this Site are owned by ghmade unless otherwise indicated and you agree not to infringe any intellectual property rights owned by ghmade.
                          </p> 
                          <p>
                          To be clear: No material on this site may be copied, reproduced, republished, installed, posted, transmitted, stored or distributed without written permission from ghmade.
                          </p>

                          <h3><strong>Meanings</strong></h3>
                          <p>For this Privacy Policy:</p>
                          <p className="ml-4">
                          <li>
                            You is referred to the person who accessed the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
                          </li>
                          <li>
                          Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to AMALITECH,
                          </li>
                          <li>
                          AMALITECH
                          </li>
                          <li>
                          Web or mobile application is referred to ghmade accessible from www.communityplatform.com, Google Playstore or App Store. Service is referred to the web or mobile application.
                          </li>
                          <li>
                          Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used. 
                          </li>
                          <li>
                          Personal Data is any information that relates to an identified or identifiable individual.
                          </li>
                          <li>
                          Cookies are a small amount of data generated by a website and saved by your web browser. Its purpose is to remember information about you, similar to a preference file created by a software application.
                          </li>
                          <li>
                          Device could be any device with internet and can access the service, such as a mobile phone, a computer or a digital tablet.
                          </li>
                          <li>
                          Usage Data is referred to the data that’s been collected automatically, either generated by the use of the Service or from the Service infrastructure itself. For example, how many times the user accessed the website.
                          </li>
                          </p>

                          <h3><strong>Restrictions</strong></h3>
                          <p>You agree not to, and you will not permit others to:</p>
                          <p className="ml-4">
                          <li>
                          License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the web or mobile application or make the platform available to any third party.
                          </li>
                          <li>
                          Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the web or mobile application. Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of ghmade or its affiliates, partners, suppliers or the licensors of the web or mobile application
                          </li>
                          </p>

                          <h3><strong>Your Suggestions</strong></h3>
                          <p>Any feedback, comments, ideas, improvements, or suggestions (collectively, "Suggestions") provided by you to ghmade with respect to the web or mobile application shall remain the sole and exclusive property of ghmade.</p>
                          <p>
                          ghmade shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.
                          </p>

                          <h3><strong>Your Consent</strong></h3>
                          <p>By using our platform, registering an account, or placing an order, you consent to this Terms & Conditions.</p>

                          <h3><strong>Links to Other Websites</strong></h3> 
                          <p>Our service may contain links to other websites that are not operated by Us. If You click on a third-party link, You will be directed to that third party's site. We strongly advise You to review the Terms & Conditions of every site You visit.</p>
                          <p>We have no control over and assume no responsibility for the content, Terms & Conditions or practices of any third-party sites or services.</p>  


                          <h3><strong>Cookies</strong></h3>
                          <p>ghmade uses "Cookies" to identify the areas of our web or mobile application that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to personalize the Content that you see in our web or mobile application. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access some functionality on our web or mobile application correctly or at all. We never place Personally Identifiable Information in Cookies. By using our site, registering an account, or placing an order, you consent to the fact that we use cookies.</p>

                          <h3><strong>Changes to Our Terms & Conditions</strong></h3>
                          <p>You acknowledge and agree that ghmade may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at ghmade’s sole discretion, with or without prior notice to you. You may stop using the Service at any time. You do not need to specifically inform ghmade when you stop using the Service. You acknowledge and agree that if ghmade disables access to your account, you may be prevented from accessing the Service, your account details or any files or other materials which is contained in your account.</p>
                          <p>If we decide to change our Terms & Conditions, we will post those changes on this page, and/or update the Terms & Conditions modification date below.</p>
                          
                          <h3><strong>Modifications to Our Web</strong></h3>
                          <p>ghmade reserves the right to modify, suspend or discontinue, temporarily or permanently, the web or mobile application or any service to which it connects, with or without notice and without liability to you.</p>

                          <h3><strong>Updates to Our Web</strong></h3>
                          <p>ghmade may from time to time provide enhancements or improvements to the features/ functionality of the web or mobile application, which may include patches, bug fixes, updates, upgrades and other modifications ("Updates").</p>
                          <p>Updates may modify or delete certain features and/or functionalities of the web or mobile application. You agree that ghmade has no obligation to (i) provide any Updates, or (ii) continue to provide or enable any particular features and/or functionalities of the web or mobile application to you.</p>
                          <p>You further agree that all Updates will be (i) deemed to constitute an integral part of the web or mobile application and (ii) subject to the terms and conditions of this Agreement.</p>

                          <h3><strong>First and Second-party Interactions</strong></h3>
                          <p>ghmade allows for interactions between two or several parties. You acknowledge and agree that ghmade shall not be responsible for any liabilities or issues that result from interactions with second parties on the platform. You sell or buy at your own risk.</p>
                          
                          <h3><strong>Data Security</strong></h3>
                          <p>ghmade takes every reasonable precaution to secure your personal data from being accidentally lost, used, or accessed in an unauthorized way, altered or disclosed.</p>
                          <p>The security of your personal information is central to ghmade. We follow global industry standards to protect the personal information submitted to us in any transaction on the platform. No method of transaction over the Internet, or method of electronic storage, is 100% secure, however. Therefore, while we strive to use commercially acceptable means to protect your personal information, we cannot guarantee its absolute security.</p>
                          <p>If you have any questions about security on our Web site, you can email us at info@communitypatform.com</p>
                          


                          <h3><strong>Use of Language</strong></h3>
                          <p>You may ensure that whatever you write must be clear and conspicuous (plain language) and in a manner that meets regulatory requirements. It must as well be (among other elements) be truthful, easily seen, and written in English language.</p>



                          <h3><strong>ghmade’s Rights</strong></h3>
                          <p>ghmade and its assigned agents reserve the right to remove your membership from the ghmade should you violate the ghmade’s Terms and Conditions.</p>


                          <h3><strong>Term and Termination</strong></h3>
                          <p>This Agreement shall remain in effect until terminated by you or ghmade.
                              ghmade may, in its sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice.
                          </p>
                          <p>This Agreement will terminate immediately, without prior notice from ghmade, in the event that you fail to comply with any provision of this Agreement. You may also terminate this Agreement by deleting the web or mobile application and all copies thereof from your computer or gadget.</p>
                          <p>Upon termination of this Agreement, you shall cease all use of the application and delete all copies of the application from your computer.</p>
                          <p>Termination of this Agreement will not limit any of ghmade's rights or remedies at law or in equity in case of breach by you (during the term of this Agreement) of any of your obligations under the present Agreement.</p>
                         
                          <h3><strong>Indemnification</strong></h3>
                          <p>You agree to indemnify and hold ghmade and its parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (if any) harmless from any claim or demand, including reasonable attorneys' fees, due to or arising out of your: (a) use of the web or mobile application; (b) violation of this Agreement or any law or regulation; or (c) violation of any right of a third party.</p>


                          <h3><strong>No Warranties</strong></h3>
                          <p>The web or mobile application is provided to you "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, ghmade, on its own behalf and on behalf of its affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the web application, including all implied warranties of merchantability, fitness for a particular purpose, title and noninfringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, ghmade provides no warranty or undertaking, and makes no representation of any kind that the web or mobile application will meet your requirements, achieve any intended results, be compatible or work with any other software, web or mobile application, systems or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected.</p>
                          <p>Without limiting the foregoing, neither ghmade nor any ghmade's provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the web or mobile application, or the information, content, and materials or products included thereon; (ii) that the web or mobile application will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the web or mobile application; or (iv) that the web or mobile application, its servers, the content, or e-mails sent from or on behalf of ghmade are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components.</p>
                          <p>Some jurisdictions do not allow the exclusion of or limitations on implied warranties or the limitations on the applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to you.</p>
                          
                          <h3><strong>Limitation of Liability</strong></h3>
                          <p>To the maximum extent permitted by applicable law, in no event shall ghmade or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, for loss of data or other information, for business interruption, for personal injury, for loss of privacy arising out of or in any way related to the use of or inability to use the web or mobile application, third-party software and/or third-party hardware used with the web or mobile application, or otherwise in connection with any provision of this Agreement), even if ghmade or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose.</p>
                          <p>Some states/jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you.</p>
                             
                          <h3><strong>Severability</strong></h3>
                          <p>If any provision of this Agreement is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.</p>

                          <h3><strong>Waiver</strong></h3>
                          <p>Except as provided herein, the failure to exercise a right or to require performance of an obligation under this Agreement shall not affect a party's ability to exercise such right or require such performance at any time thereafter nor shall be the waiver of a breach constitute waiver of any subsequent breach.</p>

                          <h3><strong>Amendments to this Agreement</strong></h3>
                          <p>ghmade reserves the right, at its sole discretion, to modify or replace this Agreement at any time. If a revision is material, we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>
                          <p>By continuing to access or use our web or mobile application, after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use ghmade</p>
                          
                          
                          <h3><strong>Entire Agreement</strong></h3>
                          <p>The Agreement constitutes the entire agreement between You and ghmade regarding your use of the web or mobile application and supersedes all prior and contemporaneous written or oral agreements between you and ghmade.</p>

                          <h3><strong>Breach of Terms and Conditions </strong></h3>
                          <p>
                            <ol>
                              <li>
                                If we permit the registration of an account on our marketplace, it will remain open indefinitely, subject to these general terms and conditions.
                                </li>
                              <li>
                              <p> If you breach these general terms and conditions, or if we reasonably suspect that you have breached these general terms and conditions or any of the ghmade's codes, policies or guidelines in any way we may: </p>
                                  <p>- temporarily suspend your access to the ghmade.</p>
                                  <p>- permanently prohibit you from accessing the ghmade.</p>
                                  <p>- commence legal action against you, whether for breach of contract or otherwise.</p>  
                              </li>
                              <li>
                              Where we suspend, prohibit, or block your access to the ghmade you must not take any action to circumvent such suspension or prohibition or blocking (including without limitation creating and/or using a different account).
                              </li>
                            </ol>
                          </p>

                          <h3><strong>Disclaimer</strong></h3>
                          <p>ghmade is not responsible for any content, code, or any other imprecision.</p>
                          <p>ghmade does not provide warranties or guarantees. In no event shall ghmade be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. The Company reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.</p>
                          
                          
                          <h3><strong>Feedback</strong></h3>
                          <p>We always appreciate your feedback or other suggestions about ghmade, but you must understand that we may use your feedback or suggestions without any obligation to compensate you for them.</p>

                          <h3><strong>Contact Us</strong></h3>
                          <p>Don't hesitate to contact us if you have any questions.</p>
                          <p>Via Email: <a href="mailto:info@ghmade.com">info@ghmade.com</a>  </p>
                          <p>Via this Link: <a href="http://www.ghmade.com" target="_blank" rel="noopener noreferrer">http://www.ghmade.com</a></p>

                            <h6 className="mt-4 pb-4 d-flex justify-content-center"><strong > Last updated: September 29, 2020</strong></h6>
                </div>
          </MainLayout>

          <FooterLayout/>
        </>
    )
}

export default termsandconditions